#%RAML 1.0
properties:
  index?: integer
  name:
  lastName:
  address:
  phoneNumber:
  type:
    enum: [ FAMILY, PERSONAL ]
  relationship:
    enum: [ MOTHER, FATHER, BROTHERS, CHILDREN, OTHER ]