#%RAML 1.0
properties:
  index: integer
  customer: Customer
  inconvenient:
  counterpartVersion?:
  evaluation?:
  solution?:
  status:
    enum: [ PENDING, FINISHED, CANCELED ]
  openingDate: datetime
  closingDate?: datetime