#%RAML 1.0
usage: Apply this to any method that needs to be searchable.
description: Some requests need a specific search.
queryParameters:
  search?:
    description: The value to search.
    type: string