#%RAML 1.0
properties:
  id: number
  user: UserSimple
  registerDate: datetime
  cashRegisters: CashRegisterResponse[]
  settlement: SettlementResponse
  observations:
  totalPapers: number
  totalCoins: number
  totalCash: number
  imbalance: number
