#%RAML 1.0
displayName: Curriculum Vitae
description: |
  This resource contains all the necessary operations for the management
  of the curriculum vitaes, among these operations we will have HTTP
  methods to get all the elements, to get a single element, to edit the
  existing elements and finally to eliminate.
get:
  description: Get curriculum vitae from the given messenger ID
  queryParameters:
    messenger:
      description: The messenger ID
      type: number
      example: 1
  headers:
    Accept-Language?: !include ../../accept-language.raml
  responses:
    200:
      description: Successfull request.
      body:
        type: CurriculumVitae
    404: !include ../../errors/error-404.raml
    500: !include ../../errors/error-500.raml
/{id}:
  description: |
    A specific curriculum vitae, the curriculum vitae of messenger.
  uriParameters:
    id:
      description: Curriculum Vitae ID is required.
      type: number
  get:
    description: Get information about a curriculum vitae.
    headers:
      Accept-Language?: !include ../../accept-language.raml
    responses:
      200:
        description: Successfull request.
        body:
          type: CurriculumVitae
      400: !include ../../errors/error-400.raml
      404: !include ../../errors/error-404.raml
      500: !include ../../errors/error-500.raml
  put:
    description: |
      Update specific curriculum vitae of the messenger.
    headers:
      Accept-Language?: !include ../../accept-language.raml
    body: 
      description: The curriculum vitae data is required to update.
      type: CurriculumVitae
    responses: 
      200:
        description: It has updated a curriculum vitae.
        body:
          type: CurriculumVitae
      400: !include ../../errors/error-400.raml
      404: !include ../../errors/error-404.raml
      500: !include ../../errors/error-500.raml
  
  # References subresource
  /references: !include references.raml