#%RAML 1.0
properties:
  id: number
  refundDate?: date-only
  reason?:
  observations?:
  message?:
  operation: Operation
  messenger: MessengerSimple
  registerDate?: datetime
  approved?: boolean
  approvalDate?: datetime