#%RAML 1.0
type: collection
get:
  is: [ paged, dateFilter ]
  queryParameters:
    type?:
      description: Provide if you need to filter the list by inputs or outputs.
      enum: [ INPUT, OUTPUT ]
  responses:
    200:
      body:
        type: object
        properties:
          items: Stock[]
          total: number
        example:
          items:
            - # start item 1
              index: 1
              count: 5
              type: INPUT
              reason: This is a reason.
              registerDate: 2017-04-10T12:00:00.000Z
            - # start item 2
              index: 2
              count: 15
              type: OUTPUT
              reason: This is a reason.
              registerDate: 2017-04-10T12:00:00.000Z
          total: 10
post:
  body:
    example:
      count: 15
      type: INPUT
      reason: This is a reason.
  responses:
    201:
      body:
        example:
          index: 1
          count: 5
          type: INPUT
          reason: This is a reason.
          registerDate: 2017-04-10T12:00:00.000Z
/{index}:
  description: |
    A specific stock, a item of the stocks list.
  uriParameters:
    index:
      description: Stock index is required.
      type: integer
  get:
    description: Get information about a stock.
    headers:
      Accept-Language?: !include ../../accept-language.raml
    responses:
      200:
        description: Successfull request.
        body:
          type: Stock
          example:
            index: 1
            count: 5
            type: INPUT
            reason: This is a reason.
            registerDate: 2017-04-10T12:00:00.000Z
      400: !include ../../errors/error-400.raml
      404: !include ../../errors/error-404.raml
      500: !include ../../errors/error-500.raml