#%RAML 1.0
description: |
  It is a header indicating if the content is expected to be displayed inline in the browser,
  that is, as a Web page or as part of a Web page, or as an attachment, that is downloaded
  and saved locally.
type: string