#%RAML 1.0
properties:
  id?: number
  customerId: number
  operationId: number
  locations: Location[]
  rating: Rating
  requirements: Requirement
  periodicity?: Repeat
  createDate?: datetime