#%RAML 1.0
type: Repeat
discriminatorValue: weeklyRepeatData
properties:
  every: integer
  monday: boolean
  tuesday: boolean
  wednesday: boolean
  thursday: boolean
  friday: boolean
  saturday: boolean
  sunday: boolean